apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  namespace: dev-namespace
  labels:
    release: v1
spec:
  containers:
    - name: my-nginx-container
      image: nginx
      resources: # requests and limits for resources. This is optional.
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - name: http-port
          containerPort: 80

# kubectl get pods --namespace=dev-namespace
