apiVersion: v1
kind: Service
metadata:
  name: myapp-internal-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 80


That is absolutely okay. Every such attempt will lead her to a GRAND success, which we all know she is destined to have. An attempt should be treated positively rather than as a failure. This should also make her emotionally strong and thrive to achieve her goal. I want to see her as a successful, strong, confident woman and she will be for sure. I know you all are supporting her to get over it. I am also going to call her today evening. 