apiVersion: v1
kind: Service
metadata:
 name: my-nginx-cluster-ip-service
spec:
 type: ClusterIP # ClusterIP is the default
 selector:
    app: nginx-app
 ports:
 - port: 8080
   targetPort: 80

# kubectl apply -f services/cluster-ip-service.yml
# kubectl get service my-nginx-cluster-ip-service -o yaml
# kubectl describe service my-nginx-cluster-ip-service
# kubectl get svc
# kubectl get svc my-nginx-cluster-ip-service
# kubectl delete svc my-nginx-cluster-ip-service
# kubectl delete -f services/cluster-ip-service.yml
