apiVersion: v1
kind: Service
metadata:
 name: my-nginx-load-balancer-service
spec:
 type: LoadBalancer
 selector:
    app: nginx-app
 ports:
  - name: "http"
    port: 80
    targetPort: 80
    
  - name: "https"
    port: 443
    targetPort: 443

# This service is used to expose the load balancer.